### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by jsbrittain** [jsbrittain/GRAPEVNE#4]
- [x] opening vocpl-pipeline, switching out a node and then building, breaks connections at the new node location; new build does not redirect input_namespace of the next node in the chain to the new node.
- [x] dropdown box to select modules by repository as-well as project
- [ ] file browser system
